<a href="https://colab.research.google.com/github/peilanyang/peilanyang.github.io/blob/master/chap12_1_%E9%99%A3%E5%88%97%E5%88%9D%E5%A7%8B%E8%88%87%E8%A6%8F%E5%8A%83.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
a = np.array([[3, 4, 5],
        [7, 8, 9]])
print(a.ndim)
print(a.shape)
print(a.size)
print(a.dtype)

2
(2, 3)
6
int64


In [ ]:
# numpy 可用方法
np.empty((2,4))

array([[4.68429807e-310, 3.60739284e-313, 2.05833592e-312,
        4.68429807e-310],
       [0.00000000e+000, 0.00000000e+000, 9.88131292e-324,
        0.00000000e+000]])

In [ ]:
# numpy 可用方法
np.zeros( (3,4) ).astype('int')

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [ ]:
# numpy 可用方法
np.ones( (5,2) )

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [ ]:
# numpy 可用方法
np.full( (3,3) , 2 )

array([[2, 2, 2],
       [2, 2, 2],
       [2, 2, 2]])

In [ ]:
# numpy 可用方法
np.eye(3).astype('int')


array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [ ]:
# numpy 可用方法
np.diag( [1,2,3,4] )

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [ ]:
#################
# reshape
#################
import numpy as np
a = np.array([[3, 4, 5],
              [7, 8, 9]])
print(a.shape)
a

(2, 3)


array([[3, 4, 5],
       [7, 8, 9]])

In [ ]:
#變形
a.reshape(3, 2)

array([[3, 4],
       [5, 7],
       [8, 9]])

In [ ]:
#變形 (1,6)
a.reshape(1, -1) # 1, -1:表示COLUMN為主

array([[3, 4, 5, 7, 8, 9]])

In [ ]:
#變形 (6,1)
a.reshape(-1, 1) # -1, 1:表示ROW為主

array([[3],
       [4],
       [5],
       [7],
       [8],
       [9]])

In [ ]:
# 為何需要reshape
# 案例 建立 Machine learninge
# 特徵(資料屬性 花的長寬) vs 答案(種類)
from sklearn import datasets
iris = datasets.load_iris()
iris.data.shape, iris.target.reshape(-1, 1).shape

In [ ]:
# 為何需要reshape
# 合併
# np.hstack( (iris.data, iris.target) )
np.hstack( (iris.data, iris.target.reshape(-1, 1)) )

In [ ]:
# numpy 可用方法
# for i in range(0, 5, 0.1):
#     print(i)
import numpy as np
for i in np.arange(0, 1.1, 0.1): # 包含頭 不含尾
    print(i)

0.0
0.1
0.2
0.30000000000000004
0.4
0.5
0.6000000000000001
0.7000000000000001
0.8
0.9
1.0


In [ ]:
# numpy 可用方法
import numpy as np
for i in np.linspace(1, 5, 5): # 包含頭尾
    print(i)

1.0
2.0
3.0
4.0
5.0


In [ ]:
# Exam
import numpy as np
r1 = np.arange(25, 30, .5)
print("r1=>",r1)


r1=> [25.  25.5 26.  26.5 27.  27.5 28.  28.5 29.  29.5]


In [ ]:
# Exam
import numpy as np
lin = np.linspace(3, 5, 9)
print("r1=>",lin)


r1=> [3.   3.25 3.5  3.75 4.   4.25 4.5  4.75 5.  ]


In [ ]:
import numpy as np
a = np.array( [6, 7, 8, 9] )
b = np.arange( 4 )
#             [0, 1, 2, 3]
c = a - b
print(a)
print(b)
print(c)


[6 7 8 9]
[0 1 2 3]
[6 6 6 6]


In [ ]:
d = b**2
print("d=>",d)

d=> [0 1 4 9]


In [ ]:
########## numpy(0D, 1D, 2D, 3D, ...) --> pandas(numpy.2D)
# numpy slicing
# 重點
# 學起來
# data = pd.read_csv('example1.csv', header=None)
# data[ data[5] > 100 ] <-----解說
##########
f  = np.array([5    , -1  ,     3,     9,    0])
tf = np.array([False, True, False, False, True])
f[ tf ]

array([-1,  0])

In [ ]:
##########
# numpy slicing
# 重點
##########
f  = np.array([5    , -1  ,     3,     9,    0])
tf = (f < 3)
print(tf)
f[ tf ]

[False  True False False  True]


array([-1,  0])

In [ ]:
##########
# numpy slicing
# 重點
# 學起來
# data = pd.read_csv('example1.csv', header=None)
# data[ data[5] > 100 ] <-----解說
##########
f  = np.array([5    , -1  ,     3,     9,    0])
f[ f < 3 ]

array([-1,  0])

In [ ]:
# Exam 留下偶數 請使用 numpy slicing
import numpy as np
a = np.array([3, 4, 5, 7, 8, 9])
a[ a % 2 == 0 ]

array([4, 8])

In [ ]:
# Exam 留下奇數 且 數字 小於等於 5，請使用 numpy slicing
import numpy as np
a = np.array([3, 4, 5, 7, 8, 9])
a[(a % 2 == 1) & (a <=5)]

array([3, 5])

In [ ]:
for aa in a:
    if (aa % 2 == 1) and  (aa <=5):
        print(aa)

3
5


In [ ]:
# Exam 留下奇數 且 數字 小於等於 5，請使用 numpy slicing
%%time
import numpy as np
a = np.arange(10000000)
a[(a % 2 == 1)]

CPU times: user 200 ms, sys: 572 µs, total: 200 ms
Wall time: 202 ms


In [ ]:
%%time
import numpy as np
a = np.arange(10000000)
total = []
for aa in a:
    if (aa % 2 == 1) :
        total.append(aa)

CPU times: user 7.46 s, sys: 209 ms, total: 7.67 s
Wall time: 7.77 s
